apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Criteo.API.MS"
  description: "Testing templates"
  annotations:
    github.com/project-slug: "criteo-dexter/Criteo.API.MS"
    backstage.io/techdocs-ref: github:https://github.com/criteo-dexter/Criteo.API.MS
spec:
  type: service
  lifecycle: experimental
  owner: "canut"
